modLoader = "javafml"
loaderVersion = "[36.2,)"
license = "GPL-3.0"

[[mods]] 
modId = "gigawhat_gigamod" 
version = "0.2.1"
displayName = "Gigamod"
#logoFile = "examplemod.png"
authors = "Gigawhat Programming Team"
credits = "Samyar Sadat Akhavi, quacker2589"
description = '''
Gigamod, A Minecraft mod by Gigawhat.


§6§l§o------- Credits -------§r

§b§o---- Code ----§r
§aLead developer : Samyar Sadat Akhavi

§e§o---- Textures & Models ----§r
§7Texture design : quacker2589, Samyar Sadat Akhavi
§7Modeling : Samyar Sadat Akhavi

§9§o---- Sound ----§r
§7Sound design : Samyar Sadat Akhavi

§a§o---- Testing ----§r
§7Gigawhat Programming Team

GitHub: https://www.github.com/Gigawhat-net/Gigamod

§dCopyright © 2021 - 2022 Gigawhat Programming Team.'''

[[dependencies.gigawhat_gigamod]]

    modId = "forge"
    mandatory = true
    versionRange = "[36.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gigawhat_gigamod]]

    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16, 1.16.5)"
    ordering = "NONE"
    side = "BOTH"
